=== nojimage/local-gov-code-jp/schema.json
{
    "$id": "https://github.com/nojimage/local-gov-code-jp",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "uniqueItems": true,
    "definitions": {
    },
    "items": {
        "$id": "https://github.com/nojimage/local-gov-code-jp/item",
        "type": "object",
        "required": [
            "type",
            "code",
            "name",
            "kana"
        ],
        "definitions": {
            "code": {
                "type": "string",
                "pattern": "^[0-9]{6}$",
                "examples": [
                    "010006",
                    "011002",
                    "011011"
                ]
            },
            "optionalCode": {
                "type": [
                    "string",
                    "null"
                ],
                "pattern": "^[0-9]{6}$",
                "examples": [
                    "010006",
                    "011002",
                    "011011"
                ]
            }
        },
        "properties": {
            "type": {
                "type": "string",
                "title": "The Type Schema",
                "enum": [
                    "prefecture",
                    "city",
                    "ward"
                ]
            },
            "code": {
                "title": "The Code Schema",
                "$ref": "#/items/definitions/code"
            },
            "name": {
                "type": "string",
                "title": "The Name Schema",
                "examples": [
                    "北海道",
                    "北海道札幌市",
                    "北海道札幌市中央区"
                ]
            },
            "kana": {
                "type": "string",
                "title": "The Kana Schema",
                "examples": [
                    "ほっかいどう",
                    "ほっかいどうさっぽろし",
                    "ほっかいどうさっぽろしちゅうおうく"
                ]
            },
            "ward_code": {
                "title": "The Ward Code Schema",
                "$ref": "#/items/definitions/optionalCode"
            },
            "ward_name": {
                "type": [
                    "string",
                    "null"
                ],
                "title": "The Ward Name Schema",
                "examples": [
                    "中央区"
                ]
            },
            "ward_kana": {
                "type": [
                    "string",
                    "null"
                ],
                "title": "The Ward Kana Schema",
                "examples": [
                    "ちゅうおうく"
                ]
            },
            "city_code": {
                "title": "The City Code Schema",
                "$ref": "#/items/definitions/optionalCode"
            },
            "city_name": {
                "type": [
                    "string",
                    "null"
                ],
                "title": "The City Name Schema",
                "examples": [
                    "札幌市"
                ]
            },
            "city_kana": {
                "type": [
                    "string",
                    "null"
                ],
                "title": "The City Kana Schema",
                "examples": [
                    "さっぽろし"
                ]
            },
            "pref_code": {
                "title": "The Pref Code Schema",
                "$ref": "#/items/definitions/optionalCode"
            },
            "pref_name": {
                "type": "string",
                "title": "The Pref Name Schema",
                "examples": [
                    "北海道"
                ]
            },
            "pref_kana": {
                "type": "string",
                "title": "The Pref Kana Schema",
                "examples": [
                    "ほっかいどう"
                ]
            }
        }
    }
}

=== nojimage/local-gov-code-jp/prefectures.json
[
    {
        "type": "prefecture",
        "code": "010006",
        "name": "北海道",
        "kana": "ほっかいどう",
        "pref_code": "010006",
        "pref_name": "北海道",
        "pref_kana": "ほっかいどう"
    },
    {
        "type": "prefecture",
        "code": "020001",
        "name": "青森県",
        "kana": "あおもりけん",
        "pref_code": "020001",
        "pref_name": "青森県",
        "pref_kana": "あおもりけん"
    },
    {
        "type": "prefecture",
        "code": "030007",
        "name": "岩手県",
        "kana": "いわてけん",
        "pref_code": "030007",
        "pref_name": "岩手県",
        "pref_kana": "いわてけん"
    },
    {
        "type": "prefecture",
        "code": "040002",
        "name": "宮城県",
        "kana": "みやぎけん",
        "pref_code": "040002",
        "pref_name": "宮城県",
        "pref_kana": "みやぎけん"
    },
    {
        "type": "prefecture",
        "code": "050008",
        "name": "秋田県",
        "kana": "あきたけん",
        "pref_code": "050008",
        "pref_name": "秋田県",
        "pref_kana": "あきたけん"
    },
    {
        "type": "prefecture",
        "code": "060003",
        "name": "山形県",
        "kana": "やまがたけん",
        "pref_code": "060003",
        "pref_name": "山形県",
        "pref_kana": "やまがたけん"
    },
    {
        "type": "prefecture",
        "code": "070009",
        "name": "福島県",
        "kana": "ふくしまけん",
        "pref_code": "070009",
        "pref_name": "福島県",
        "pref_kana": "ふくしまけん"
    },
    {
        "type": "prefecture",
        "code": "080004",
        "name": "茨城県",
        "kana": "いばらきけん",
        "pref_code": "080004",
        "pref_name": "茨城県",
        "pref_kana": "いばらきけん"
    },
    {
        "type": "prefecture",
        "code": "090000",
        "name": "栃木県",
        "kana": "とちぎけん",
        "pref_code": "090000",
        "pref_name": "栃木県",
        "pref_kana": "とちぎけん"
    },
    {
        "type": "prefecture",
        "code": "100005",
        "name": "群馬県",
        "kana": "ぐんまけん",
        "pref_code": "100005",
        "pref_name": "群馬県",
        "pref_kana": "ぐんまけん"
    },
    {
        "type": "prefecture",
        "code": "110001",
        "name": "埼玉県",
        "kana": "さいたまけん",
        "pref_code": "110001",
        "pref_name": "埼玉県",
        "pref_kana": "さいたまけん"
    },
    {
        "type": "prefecture",
        "code": "120006",
        "name": "千葉県",
        "kana": "ちばけん",
        "pref_code": "120006",
        "pref_name": "千葉県",
        "pref_kana": "ちばけん"
    },
    {
        "type": "prefecture",
        "code": "130001",
        "name": "東京都",
        "kana": "とうきょうと",
        "pref_code": "130001",
        "pref_name": "東京都",
        "pref_kana": "とうきょうと"
    },
    {
        "type": "prefecture",
        "code": "140007",
        "name": "神奈川県",
        "kana": "かながわけん",
        "pref_code": "140007",
        "pref_name": "神奈川県",
        "pref_kana": "かながわけん"
    },
    {
        "type": "prefecture",
        "code": "150002",
        "name": "新潟県",
        "kana": "にいがたけん",
        "pref_code": "150002",
        "pref_name": "新潟県",
        "pref_kana": "にいがたけん"
    },
    {
        "type": "prefecture",
        "code": "160008",
        "name": "富山県",
        "kana": "とやまけん",
        "pref_code": "160008",
        "pref_name": "富山県",
        "pref_kana": "とやまけん"
    },
    {
        "type": "prefecture",
        "code": "170003",
        "name": "石川県",
        "kana": "いしかわけん",
        "pref_code": "170003",
        "pref_name": "石川県",
        "pref_kana": "いしかわけん"
    },
    {
        "type": "prefecture",
        "code": "180009",
        "name": "福井県",
        "kana": "ふくいけん",
        "pref_code": "180009",
        "pref_name": "福井県",
        "pref_kana": "ふくいけん"
    },
    {
        "type": "prefecture",
        "code": "190004",
        "name": "山梨県",
        "kana": "やまなしけん",
        "pref_code": "190004",
        "pref_name": "山梨県",
        "pref_kana": "やまなしけん"
    },
    {
        "type": "prefecture",
        "code": "200000",
        "name": "長野県",
        "kana": "ながのけん",
        "pref_code": "200000",
        "pref_name": "長野県",
        "pref_kana": "ながのけん"
    },
    {
        "type": "prefecture",
        "code": "210005",
        "name": "岐阜県",
        "kana": "ぎふけん",
        "pref_code": "210005",
        "pref_name": "岐阜県",
        "pref_kana": "ぎふけん"
    },
    {
        "type": "prefecture",
        "code": "220001",
        "name": "静岡県",
        "kana": "しずおかけん",
        "pref_code": "220001",
        "pref_name": "静岡県",
        "pref_kana": "しずおかけん"
    },
    {
        "type": "prefecture",
        "code": "230006",
        "name": "愛知県",
        "kana": "あいちけん",
        "pref_code": "230006",
        "pref_name": "愛知県",
        "pref_kana": "あいちけん"
    },
    {
        "type": "prefecture",
        "code": "240001",
        "name": "三重県",
        "kana": "みえけん",
        "pref_code": "240001",
        "pref_name": "三重県",
        "pref_kana": "みえけん"
    },
    {
        "type": "prefecture",
        "code": "250007",
        "name": "滋賀県",
        "kana": "しがけん",
        "pref_code": "250007",
        "pref_name": "滋賀県",
        "pref_kana": "しがけん"
    },
    {
        "type": "prefecture",
        "code": "260002",
        "name": "京都府",
        "kana": "きょうとふ",
        "pref_code": "260002",
        "pref_name": "京都府",
        "pref_kana": "きょうとふ"
    },
    {
        "type": "prefecture",
        "code": "270008",
        "name": "大阪府",
        "kana": "おおさかふ",
        "pref_code": "270008",
        "pref_name": "大阪府",
        "pref_kana": "おおさかふ"
    },
    {
        "type": "prefecture",
        "code": "280003",
        "name": "兵庫県",
        "kana": "ひょうごけん",
        "pref_code": "280003",
        "pref_name": "兵庫県",
        "pref_kana": "ひょうごけん"
    },
    {
        "type": "prefecture",
        "code": "290009",
        "name": "奈良県",
        "kana": "ならけん",
        "pref_code": "290009",
        "pref_name": "奈良県",
        "pref_kana": "ならけん"
    },
    {
        "type": "prefecture",
        "code": "300004",
        "name": "和歌山県",
        "kana": "わかやまけん",
        "pref_code": "300004",
        "pref_name": "和歌山県",
        "pref_kana": "わかやまけん"
    },
    {
        "type": "prefecture",
        "code": "310000",
        "name": "鳥取県",
        "kana": "とっとりけん",
        "pref_code": "310000",
        "pref_name": "鳥取県",
        "pref_kana": "とっとりけん"
    },
    {
        "type": "prefecture",
        "code": "320005",
        "name": "島根県",
        "kana": "しまねけん",
        "pref_code": "320005",
        "pref_name": "島根県",
        "pref_kana": "しまねけん"
    },
    {
        "type": "prefecture",
        "code": "330001",
        "name": "岡山県",
        "kana": "おかやまけん",
        "pref_code": "330001",
        "pref_name": "岡山県",
        "pref_kana": "おかやまけん"
    },
    {
        "type": "prefecture",
        "code": "340006",
        "name": "広島県",
        "kana": "ひろしまけん",
        "pref_code": "340006",
        "pref_name": "広島県",
        "pref_kana": "ひろしまけん"
    },
    {
        "type": "prefecture",
        "code": "350001",
        "name": "山口県",
        "kana": "やまぐちけん",
        "pref_code": "350001",
        "pref_name": "山口県",
        "pref_kana": "やまぐちけん"
    },
    {
        "type": "prefecture",
        "code": "360007",
        "name": "徳島県",
        "kana": "とくしまけん",
        "pref_code": "360007",
        "pref_name": "徳島県",
        "pref_kana": "とくしまけん"
    },
    {
        "type": "prefecture",
        "code": "370002",
        "name": "香川県",
        "kana": "かがわけん",
        "pref_code": "370002",
        "pref_name": "香川県",
        "pref_kana": "かがわけん"
    },
    {
        "type": "prefecture",
        "code": "380008",
        "name": "愛媛県",
        "kana": "えひめけん",
        "pref_code": "380008",
        "pref_name": "愛媛県",
        "pref_kana": "えひめけん"
    },
    {
        "type": "prefecture",
        "code": "390003",
        "name": "高知県",
        "kana": "こうちけん",
        "pref_code": "390003",
        "pref_name": "高知県",
        "pref_kana": "こうちけん"
    },
    {
        "type": "prefecture",
        "code": "400009",
        "name": "福岡県",
        "kana": "ふくおかけん",
        "pref_code": "400009",
        "pref_name": "福岡県",
        "pref_kana": "ふくおかけん"
    },
    {
        "type": "prefecture",
        "code": "410004",
        "name": "佐賀県",
        "kana": "さがけん",
        "pref_code": "410004",
        "pref_name": "佐賀県",
        "pref_kana": "さがけん"
    },
    {
        "type": "prefecture",
        "code": "420000",
        "name": "長崎県",
        "kana": "ながさきけん",
        "pref_code": "420000",
        "pref_name": "長崎県",
        "pref_kana": "ながさきけん"
    },
    {
        "type": "prefecture",
        "code": "430005",
        "name": "熊本県",
        "kana": "くまもとけん",
        "pref_code": "430005",
        "pref_name": "熊本県",
        "pref_kana": "くまもとけん"
    },
    {
        "type": "prefecture",
        "code": "440001",
        "name": "大分県",
        "kana": "おおいたけん",
        "pref_code": "440001",
        "pref_name": "大分県",
        "pref_kana": "おおいたけん"
    },
    {
        "type": "prefecture",
        "code": "450006",
        "name": "宮崎県",
        "kana": "みやざきけん",
        "pref_code": "450006",
        "pref_name": "宮崎県",
        "pref_kana": "みやざきけん"
    },
    {
        "type": "prefecture",
        "code": "460001",
        "name": "鹿児島県",
        "kana": "かごしまけん",
        "pref_code": "460001",
        "pref_name": "鹿児島県",
        "pref_kana": "かごしまけん"
    },
    {
        "type": "prefecture",
        "code": "470007",
        "name": "沖縄県",
        "kana": "おきなわけん",
        "pref_code": "470007",
        "pref_name": "沖縄県",
        "pref_kana": "おきなわけん"
    }
]
